

clc
clear all
close all

run('lib/addpath_recurse');
addpath_recurse('src/');
addpath_recurse('lib/');

%% LOAD DATA GENERATED BY STARAS-Julia

network_density=[0.020202020202020204, 0.04040404040404041, 0.06060606060606061, 0.08080808080808081, 0.10101010101010101, 0.12121212121212122, 0.1414141414141414, 0.16161616161616163, 0.18181818181818182, 0.20202020202020202, 0.2222222222222222, 0.24242424242424243];

%Average Bacterial Density
meanOD_0=[35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517199, 35688741.935517192];
meanOD_25=[34692454.626038678, 34020236.265555203, 33697870.681234643, 33562751.423854239, 33500959.045293879, 33467923.282296356, 33448338.46969799, 33435473.117200863, 33426522.706265215, 33419996.836041357, 33414939.903443519, 33410997.412261918];
meanOD_50=[34318404.533146091, 32903496.189235698, 32124313.882360015, 31776950.108504683, 31614362.056283638, 31528986.863339499, 31477546.136610013, 31444477.076562136, 31421154.764983125, 31404165.509226054, 31391088.221286181, 31380842.658308297];
meanOD_75=[34080761.657273985, 32008628.921913099, 30770665.760867994, 30201225.308282092, 29934278.450218126, 29792937.947976138, 29708947.236162603, 29654311.124403741, 29616767.247438412, 29588849.449892145, 29567700.493383277, 29551285.096832357];
meanOD_100=[33905977.249079995, 31240235.574757386, 29569097.340173237, 28789622.807425611, 28419308.493648503, 28224914.240600891, 28110264.282759469, 28035588.114476737, 27983751.750608444, 27945981.210580494, 27917273.863469049, 27894732.918724027];
meanOD_200=[33466540.923349325, 28896894.324017256, 25766744.711825117, 24295815.437896214, 23598586.545871966, 23232701.26023845, 23018859.273783203, 22879792.725427501, 22784801.780974548, 22715640.651098795, 22664165.523195203, 22623710.599261329];

%Relative frequency of resistance

relFreq_0=[0.39421366713981498, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981504, 0.39421366713981498];
relFreq_25=[0.39951396963477542, 0.40492145474948749, 0.40773416227502229, 0.40894089427438751, 0.40948864130843665, 0.40977565091500578, 0.40994207380546605, 0.41004910471242045, 0.41012218049485832, 0.41017459306368054, 0.4102146096810797, 0.41024540414780564];
relFreq_50=[0.40092476741515282, 0.41203092687039117, 0.41902102089215915, 0.42230596013302868, 0.42385524906276983, 0.4246592384204344, 0.42513507688128516, 0.4254355993518234, 0.42564409344602444, 0.42579382716684655, 0.42590762156319883, 0.42599576894805291];
relFreq_75=[0.40172207860011233, 0.41785011854554849, 0.42930856097552417, 0.4350146561869298, 0.43774801365097588, 0.43918775514882802, 0.44003112758208268, 0.44057125815564641, 0.44093707577599345, 0.44120547111476172, 0.44140644389315681, 0.44156087417549977];
relFreq_100=[0.40227637183631737, 0.42299000874032266, 0.43897215544810403, 0.44723116315971129, 0.45129386675145378, 0.45342986341463465, 0.45467605875711353, 0.45547665304415214, 0.45602483172780067, 0.45641942850035072, 0.45671609384998219, 0.45694677654157839];
relFreq_200=[0.40359368326330525, 0.43971481099389775, 0.47357494477618195, 0.49265325064518439, 0.50244307944844013, 0.50771153608294062, 0.51079597830819079, 0.51278656059534222, 0.51413382636566274, 0.51510490866969227, 0.51582118903477125, 0.51637930647780994];


%% Plot network density vs OD

figure(); clf('reset');set(gcf,'DefaultLineLineWidth',1); set(gcf, 'color', 'white'); hold all


CT=flipud(cbrewer('seq', 'YlOrRd', 6));
CT(1,:)=[0 0 0];

p0=plot(network_density, meanOD_0, 'Color',CT(1,:),'LineWidth',3); hold on;
p25=plot(network_density, meanOD_25, 'Color',CT(2,:),'LineWidth',3); hold on;
p50=plot(network_density, meanOD_50, 'Color',CT(3,:),'LineWidth',3); hold on;
p75=plot(network_density, meanOD_75, 'Color',CT(4,:),'LineWidth',3); hold on;
p100=plot(network_density, meanOD_100, 'Color',CT(5,:),'LineWidth',3); hold on;
%plot(network_density, meanOD_200, 'Color',CT(6,:),'LineWidth',3); hold on;

axis([0.015 .25 2.7e7 3.6e7]);

set(gca,'FontSize',20); 
xlabel('Network density','FontSize',24);
ylabel('Total bacterial density','FontSize',24);

%{
colormap(flipud(CT));
cbh=colorbar;
cbh.Ticks=linspace(0,1,length(network_density));
cbh.TickLabels=round(network_density*100)/100;
ylabel(cbh,'Antibiotic concentration','FontSize',24);
%}

legend([p0,p25,p50,p75,p100],{'No drug','A=25', 'A=50', 'A=75', 'A=100'}, 'Location','NorthEastOutside','FontSize',24);
%legend([p0,p25,p50,p75,p100,p200],{'No drug','A=25', 'A=50', 'A=75', 'A=100', 'A=200'}, 'Location','NorthEastOutside','FontSize',24);
legend boxoff


export_fig '../../figures/src/figure5_NetDen_TotDen.pdf'

%% Plot network density vs OD(T)

figure(); clf('reset');set(gcf,'DefaultLineLineWidth',1); set(gcf, 'color', 'white'); hold all

As=[0, 25, 50, 75, 100];


CT=(cbrewer('seq', 'BuPu', length(network_density)+5));
CT=flipud(CT(6:end,:));

for ii=1:length(network_density)
    
    i=length(network_density)-ii+1;

    meanODTs=[meanOD_0(i), meanOD_25(i), meanOD_50(i), meanOD_75(i), meanOD_100(i)];
    plot(As, meanODTs,'-','Color',CT(ii,:),'LineWidth',2); hold on;
end
colormap(flipud(CT(1:end,:)));
cbh=colorbar;
cbh.Ticks=linspace(0,1,length(network_density));
cbh.TickLabels=round(network_density*100)/100;
ylabel(cbh,'Network density','FontSize',24);

%axis([0.015 .25 2.2e7 3.6e7]);

set(gca,'FontSize',20); 
xlabel('Antibiotic concentration','FontSize',24);
ylabel('Total bacterial density','FontSize',24);


export_fig '../../figures/src/figure5_A_TotDen.pdf'

%% Plot network density vs relFreq

figure(); clf('reset');set(gcf,'DefaultLineLineWidth',1); set(gcf, 'color', 'white'); hold all

CT=(cbrewer('seq', 'YlOrRd', 6));
CT(1,:)=[0 0 0];


p0=plot(network_density, relFreq_0, 'Color',CT(1,:),'LineWidth',3); hold on;
p25=plot(network_density, relFreq_25, 'Color',CT(2,:),'LineWidth',3); hold on;
p50=plot(network_density, relFreq_50, 'Color',CT(3,:),'LineWidth',3); hold on;
p75=plot(network_density, relFreq_75, 'Color',CT(4,:),'LineWidth',3); hold on;
p100=plot(network_density, relFreq_100, 'Color',CT(5,:),'LineWidth',3); hold on;
%p200=plot(network_density, relFreq_200, 'Color',CT(6,:),'LineWidth',3); hold on;


set(gca,'FontSize',20); 
xlabel('Network density','FontSize',24);
ylabel('Fraction of resistance','FontSize',24);

legend([p0,p25,p50,p75,p100],{'No drug','A=25', 'A=50', 'A=75', 'A=100'}, 'Location','NorthEastOutside','FontSize',24);
%legend([p0,p25,p50,p75,p100,p200],{'No drug','A=25', 'A=50', 'A=75', 'A=100', 'A=200'}, 'Location','NorthEastOutside','FontSize',24);
legend boxoff


%{
colormap(flipud(CT));
cbh=colorbar;
yax=linspace(0,1,length(As)+1);
cbh.Ticks=yax(2)/2+yax;
cbh.TickLabels=As(1)+As;
ylabel(cbh,'Antibiotic concentration','FontSize',24);
%}

export_fig '../../figures/src/figure5_NetDen_relFreq.pdf'

%% Plot network density vs OD(T)

figure(); clf('reset');set(gcf,'DefaultLineLineWidth',1); set(gcf, 'color', 'white'); hold all

As=[0, 25, 50, 75, 100];


CT=(cbrewer('seq', 'BuPu', length(network_density)+5));
CT=flipud(CT(6:end,:));

for ii=1:length(network_density)
    i=length(network_density)-ii+1;

    relFreqs=[relFreq_0(i), relFreq_25(i), relFreq_50(i), relFreq_75(i), relFreq_100(i)];
    plot(As, relFreqs,'-','Color',CT(ii,:),'LineWidth',2); hold on;
end
colormap(flipud(CT(1:end,:)));
cbh=colorbar;
cbh.Ticks=linspace(0,1,length(network_density));
cbh.TickLabels=round(network_density*100)/100;
ylabel(cbh,'Network density','FontSize',24);

%axis([0.015 .25 2.2e7 3.6e7]);

set(gca,'FontSize',20); 
xlabel('Antibiotic concentration','FontSize',24);
ylabel('Frequency of resistance','FontSize',24);


export_fig '../../figures/src/figure5_A_RelFreq.pdf'

