

clc
clear all
close all

run('lib/addpath_recurse');
addpath_recurse('src/');
addpath_recurse('lib/');

%% LOAD DATA GENERATED BY STARAS-Julia: sim_DR.sh

nexpe=8000;
As=[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.  75.  80.];

sucWin_complete=[8000, 7000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]';
resWin_complete=[0, 1000, 8000, 7000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]';
noWin_complete=nexpe-(sucWin_complete+resWin_complete);

sucWin_wheel=[8000, 5238, 1762, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]';
resWin_wheel=[0, 2762, 5357, 7000, 5280, 3508, 3516, 3492, 1736, 1756, 1762, 0, 0, 0, 0, 0, 0]';
noWin_wheel=nexpe-(sucWin_wheel+resWin_wheel);

sucWin_star=[8000, 7000, 5208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]';
resWin_star=[0, 133, 1924, 7000, 7000, 5202, 5196, 5208, 5340, 5298, 5286, 5070, 5310, 0, 0, 0, 0]';
noWin_star=nexpe-(sucWin_star+resWin_star);

sucWin_cycle=[8000, 5000, 5000, 3000, 3000, 3000, 3000, 3000, 3000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]';
resWin_cycle=[0, 3000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 4000, 2000, 2000, 2000, 2000, 2000, 2000, 2000]';
noWin_cycle=nexpe-(sucWin_cycle+resWin_cycle);

%%


figure(1); clf('reset');set(gcf,'DefaultLineLineWidth',1); set(gcf, 'color', 'white'); hold all
set(gcf,'Units','Pixels','Position',[1000         918         434         342*2])

subaxis(4, 1, 1, 'SpacingVert', 0.05,'PaddingLeft',0.1);
h1=bar(As, [resWin_complete sucWin_complete noWin_complete]*100./nexpe, 0.9, 'stack');
set(gca,'fontsize',16); 
xticks([]);
ylim([0 100]);
xlim([-2.5 82.5]);
set(h1,{'FaceColor'},{'c';'y';[.95 .95 .95]});
set(h1,{'EdgeColor'},{'c';'y';[.95 .95 .95]});
legend('Resistant','Susceptible','No growth');
legend boxoff

subaxis(4, 1, 2, 'SpacingVert', 0.05,'PaddingLeft',0.1);
h2=bar(As, [resWin_wheel sucWin_wheel noWin_wheel]*100./nexpe, 0.9, 'stack');
set(gca,'fontsize',16); 
xticks([]);
ylim([0 100]);
xlim([-2.5 82.5]);
set(h2,{'FaceColor'},{'c';'y';[.95 .95 .95]});
set(h2,{'EdgeColor'},{'c';'y';[.95 .95 .95]});

subaxis(4, 1, 3, 'SpacingVert', 0.05,'PaddingLeft',0.1);
h3=bar(As, [resWin_star sucWin_star noWin_star]*100./nexpe, 0.9, 'stack');
set(gca,'fontsize',16); 
ylabel('                           Micro-environments colonized (%)','FontSize',18);
xticks([]);
ylim([0 100]);
xlim([-2.5 82.5]);
set(h3,{'FaceColor'},{'c';'y';[.95 .95 .95]});
set(h3,{'EdgeColor'},{'c';'y';[.95 .95 .95]});

subaxis(4, 1, 4, 'SpacingVert', 0.05,'PaddingLeft',0.1);
h4=bar(As, [resWin_cycle sucWin_cycle noWin_cycle]*100./nexpe, 0.9, 'stack');
set(gca,'fontsize',16); 
ylim([0 100]);
xlim([-2.5 82.5]);
set(h4,{'FaceColor'},{'c';'y';[.95 .95 .95]});
set(h4,{'EdgeColor'},{'c';'y';[.95 .95 .95]});

xlabel('Antibiotic concentration','FontSize',18);



export_fig '../../figures/src/figure5_topology.pdf'